<?php

/**
 * @file
 * Enables search integration with Ting.
 */


function bibsdb_open_platform_search($query) {
  $parameters = array(
    "fields" => array(
      "title",
      "creator",
      "pid",
      'coverUrlFull',
    ),
    "pretty" => true,
    "timings" => true,
    "q" => $query,
    "offset" => 0,
    "limit" => 20,
    "sort" => "date_descending",
  );
  return bibsdb_open_platform_request('search', $parameters);
}

function bibsdb_open_platform_search_collection($query) {
  $parameters = array(
    "fields" => array(
      "title",
      "collection",
      "creator",
      "pid",
    ),
    "pretty" => true,
    "q" => $query,
    "offset" => 0,
    "limit" => 15,
  );
  return bibsdb_open_platform_request('search', $parameters);
}

function bibsdb_open_platform_recommender($ids, $number_of_objects = 20) {
  $parameters = array(
    "fields" => array(
      "title",
      "creator",
      "pid",
    ),
    "pretty" => true,
    "like" => $ids,
    "recommender" => 'default',
    "limit" => $number_of_objects,
  );
  return bibsdb_open_platform_request('recommend', $parameters);
}

function bibsdb_open_platform_get_token() {
  $key = "1ba2428f-1fc3-4159-82ff-869b87026bcd";
  $secret = "3ab379e23032f8e94599ba2a75be13a4d49e846342d101a6899b27b823abff1e";

// request token
  $basic_credentials = base64_encode($key.':'.$secret);
  $tk = curl_init('https://auth.dbc.dk/oauth/token');
  curl_setopt($tk, CURLOPT_HTTPHEADER, array('Authorization: Basic '.$basic_credentials, 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8'));
  curl_setopt($tk, CURLOPT_POSTFIELDS, 'grant_type=password&username=@773000&password=@773000');
  curl_setopt($tk, CURLOPT_RETURNTRANSFER, true);
  $token = json_decode(curl_exec($tk));
  curl_close($tk);  
  return $token;
}

function bibsdb_open_platform_request($operation, $parameters) {
  $token = variable_get('bibsdb_open_platform_token', '8fcb2229d117ac2912fec4d272df3986cb415140');
  $parameters['access_token'] = '6c29a4e96187cd8951e85202f05a01f09eaf65ee';
  $service_url = 'https://openplatform.dbc.dk/v1/' . $operation;
  
  $curl = curl_init($service_url);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array(                                                                          
    'Content-Type: application/json',                                                                                
    'Accept: application/json')                                                                       
  ); 
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($curl, CURLOPT_POST, true);
  curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($parameters));
  $curl_response = curl_exec($curl);
  if ($curl_response === false) {
    $info = curl_getinfo($curl);
    curl_close($curl);
  }
  curl_close($curl);
  $decoded = json_decode($curl_response);
  if (isset($decoded->response->status) && $decoded->response->status == 'ERROR') {
    //TODO Handle error
  }
  return  $decoded;
}


