<?php

/**
 * @file
 * Enables search integration with Ting.
 */


function bibsdb_open_platform_search($query, $offset) {
  $parameters = array(
    "fields" => array(
      "title",
      "creator",
      "acIdentifier",
      'coverUrlFull',
    ),
    "pretty" => true,
    "timings" => true,
    "q" => $query,
    "offset" => $offset,
    "limit" => 16,
    "sort" => "acquisitionDate_descending",
  );
  return bibsdb_open_platform_request('search', $parameters);
}

function bibsdb_open_platform_search_collection($query) {
  $parameters = array(
    "fields" => array(
      "title",
      "collection",
      "creator",
      "acIdentifier",
    ),
    "pretty" => true,
    "q" => $query,
    "offset" => 0,
    "limit" => 16,
  );
  return bibsdb_open_platform_request('search', $parameters);
}

function bibsdb_open_platform_recommender($ids, $number_of_objects = 20) {
  $parameters = array(
    "fields" => array(
      "title",
      "creator",
      "pid",
    ),
    "pretty" => true,
    "like" => $ids,
    "recommender" => 'default',
    "limit" => $number_of_objects,
  );
  return bibsdb_open_platform_request('recommend', $parameters);
}

/**
 * Implements hook_cron().
 * Calls function to renew token.
 */
function bibsdb_open_platform_cron() {
  bibsdb_open_platform_get_token();
}


function bibsdb_open_platform_get_token() {

  $key = variable_get('open_platform_client_id');
  $secret = variable_get('open_platform_client_secret');

  // request token
  $basic_credentials = base64_encode($key.':'.$secret);
  $tk = curl_init('https://auth.dbc.dk/oauth/token');
  curl_setopt($tk, CURLOPT_HTTPHEADER, array('Authorization: Basic '.$basic_credentials, 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8'));
  curl_setopt($tk, CURLOPT_POSTFIELDS, 'grant_type=password&username=@754000&password=@754000');
  curl_setopt($tk, CURLOPT_RETURNTRANSFER, true);
  $token = json_decode(curl_exec($tk));
  curl_close($tk); 

  // save token
  variable_set('open_platform_token', $token);
  return $token;
}

function bibsdb_open_platform_request($operation, $parameters) {
  $token = variable_get('open_platform_token');
  if (!(isset($token->access_token))) {
    $token = bibsdb_open_platform_get_token();
  }
  $parameters['access_token'] = $token->access_token;
  $service_url = 'https://openplatform.dbc.dk/v1/' . $operation;
  
  $curl = curl_init($service_url);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array(                                                                          
    'Content-Type: application/json',                                                                                
    'Accept: application/json')                                                                       
  ); 
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($curl, CURLOPT_POST, true);
  curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($parameters));
  $curl_response = curl_exec($curl);
  if ($curl_response === false) {
    $info = curl_getinfo($curl);
    curl_close($curl);
  }
  curl_close($curl);
  $decoded = json_decode($curl_response);
  return  $decoded;
}


